"""Private, content-addressed object storage. SDK imports stay inside the server factory."""
from contextlib import asynccontextmanager
from dataclasses import dataclass
import base64
import hashlib
import re
from typing import Protocol


@dataclass(frozen=True)
class ObjectInfo:
    content_hash: str
    size: int


class ObjectStore(Protocol):
    async def put(self, body: bytes) -> ObjectInfo: ...
    async def get(self, content_hash: str) -> bytes | None: ...
    async def head(self, content_hash: str) -> ObjectInfo | None: ...


def _key(content_hash: str) -> str:
    # Only hashes generated by treg or read from its archive are accepted, never a path or URL.
    if not re.fullmatch(r"[0-9a-f]{64}", content_hash):
        raise ValueError("invalid archive content hash")
    return content_hash


def _missing(exc: Exception) -> bool:
    return getattr(exc, "response", {}).get("Error", {}).get("Code") in ("404", "NoSuchKey", "NotFound")


class R2ObjectStore:
    def __init__(self, client, bucket: str, max_body_bytes: int):
        self._client, self._bucket, self._max_bytes = client, bucket, max_body_bytes

    async def put(self, body: bytes) -> ObjectInfo:
        if len(body) > self._max_bytes:
            raise ValueError("archive body too large")
        digest = hashlib.sha256(body).digest()
        key = digest.hex()
        # A single PUT with an explicit SHA-256 checksum validates bytes in transit. No multipart
        # ETag assumptions, remote paths, or response-specific metadata under a shared hash.
        checksum = base64.b64encode(digest).decode("ascii")
        reply = await self._client.put_object(
            Bucket=self._bucket, Key=key, Body=body, ContentType="application/octet-stream",
            ChecksumSHA256=checksum, Metadata={"sha256": key})
        if reply.get("ChecksumSHA256", checksum) != checksum:
            raise ValueError("archive upload checksum mismatch")
        info = await self.head(key)
        if info != ObjectInfo(key, len(body)):
            raise ValueError("archive object verification failed")
        return info

    async def head(self, content_hash: str) -> ObjectInfo | None:
        key = _key(content_hash)
        try:
            reply = await self._client.head_object(Bucket=self._bucket, Key=key)
        except Exception as exc:
            if _missing(exc):
                return None
            raise
        if reply.get("Metadata", {}).get("sha256") != key:
            raise ValueError("archive object metadata mismatch")
        return ObjectInfo(key, int(reply["ContentLength"]))

    async def get(self, content_hash: str) -> bytes | None:
        key = _key(content_hash)
        try:
            reply = await self._client.get_object(Bucket=self._bucket, Key=key)
        except Exception as exc:
            if _missing(exc):
                return None
            raise
        async with reply["Body"] as stream:
            if int(reply["ContentLength"]) > self._max_bytes:
                raise ValueError("archive object too large")
            chunks, size = [], 0
            while chunk := await stream.read(min(65536, self._max_bytes + 1 - size)):
                chunks.append(chunk)
                size += len(chunk)
                if size > self._max_bytes:
                    raise ValueError("archive object too large")
            body = b"".join(chunks)
        if len(body) > self._max_bytes or hashlib.sha256(body).hexdigest() != key:
            raise ValueError("archive download checksum mismatch")
        return body


@asynccontextmanager
async def open_r2(settings):
    from aiobotocore.config import AioConfig
    from aiobotocore.session import get_session

    config = AioConfig(
        connect_timeout=settings.archive_r2_timeout_s,
        read_timeout=settings.archive_r2_timeout_s,
        retries={"total_max_attempts": 1},
        max_pool_connections=max(16, settings.archive_r2_upload_concurrency),
        request_checksum_calculation="when_required",
        response_checksum_validation="when_required")
    async with get_session().create_client(
        "s3", region_name="auto", config=config,
        endpoint_url=settings.archive_object_store_endpoint,
        aws_access_key_id=settings.archive_object_store_access_key_id,
        aws_secret_access_key=settings.archive_object_store_secret_access_key,
    ) as client:
        yield R2ObjectStore(client, settings.archive_object_store_bucket, settings.archive_max_body_bytes)
