"""Private, content-addressed object storage. SDK imports stay inside the server factory."""
from contextlib import asynccontextmanager
from dataclasses import dataclass
import hashlib
import re
from typing import Protocol


@dataclass(frozen=True)
class ObjectInfo:
    content_hash: str
    size: int


class ObjectStore(Protocol):
    async def put(self, body: bytes) -> ObjectInfo: ...
    async def get(self, content_hash: str) -> bytes | None: ...
    async def head(self, content_hash: str) -> ObjectInfo | None: ...


def _key(content_hash: str) -> str:
    # Only hashes generated by treg or read from its archive are accepted, never a path or URL.
    if not re.fullmatch(r"[0-9a-f]{64}", content_hash):
        raise ValueError("invalid archive content hash")
    return content_hash


class R2ObjectStore:
    def __init__(self, client, max_body_bytes: int, not_found: type[Exception]):
        self._client, self._max_bytes, self._not_found = client, max_body_bytes, not_found

    async def put(self, body: bytes) -> ObjectInfo:
        if len(body) > self._max_bytes:
            raise ValueError("archive body too large")
        key = hashlib.sha256(body).hexdigest()
        await self._client.put_async(
            key, body, attributes={"Content-Type": "application/octet-stream"},
            use_multipart=False)
        return ObjectInfo(key, len(body))

    async def head(self, content_hash: str) -> ObjectInfo | None:
        key = _key(content_hash)
        try:
            meta = await self._client.head_async(key)
        except (self._not_found, FileNotFoundError):
            return None
        return ObjectInfo(key, int(meta["size"]))

    async def get(self, content_hash: str) -> bytes | None:
        key = _key(content_hash)
        try:
            result = await self._client.get_async(key)
        except (self._not_found, FileNotFoundError):
            return None
        if result.meta["size"] > self._max_bytes:
            raise ValueError("archive object too large")
        body = bytes(await result.bytes_async())
        if len(body) > self._max_bytes or hashlib.sha256(body).hexdigest() != key:
            raise ValueError("archive download checksum mismatch")
        return body


@asynccontextmanager
async def open_r2(settings):
    from obstore.exceptions import NotFoundError
    from obstore.store import S3Store

    client = S3Store(
        settings.archive_object_store_bucket,
        config={
            "endpoint": settings.archive_object_store_endpoint, "region": "auto",
            "access_key_id": settings.archive_object_store_access_key_id,
            "secret_access_key": settings.archive_object_store_secret_access_key,
            "checksum_algorithm": "SHA256",
        },
        client_options={"timeout": f"{settings.archive_r2_timeout_s}s",
                        "connect_timeout": f"{settings.archive_r2_timeout_s}s"},
        retry_config={"max_retries": 0})
    # One shared Rust HTTP pool for the lifespan. S3Store has no explicit close operation;
    # dropping the store after archive drains releases its client and pool.
    yield R2ObjectStore(client, settings.archive_max_body_bytes, NotFoundError)
